import type { Indicator } from './types.js';

/**
 * The controlled indicator library.
 *
 * Calculation, unit, reporting period, data source, missing-data rule,
 * direction of harm, type and notes are carried through VERBATIM from the
 * source data dictionary (Quality Trend Tracker Indicator Data Dictionary.xlsx).
 * They are not reinterpreted anywhere in this codebase.
 *
 * `short`, `dp`, `kloe`, `reg`, `num` and `den` were added for this build and
 * are presentation and mapping metadata only.
 */
export const INDICATORS: readonly Indicator[] = [
  {
    id: "Q01",
    domain: "Quality & Safety",
    name: "Incident rate",
    short: "Incident rate",
    calc: "(Count of relevant incidents recorded in period / total resident-days in period) x 1,000",
    unit: "Rate per 1,000 resident-days",
    period: "Monthly",
    source: "Incident log; occupancy record for resident-days",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Lagging",
    notes: "Define 'relevant incident' against the home's existing incident categories before build, so it isn't decided ad hoc by whoever writes the ingestion logic.",
    example: "",
    kloe: "Safe",
    reg: "Reg 12 — Safe care and treatment",
    num: "Relevant incidents",
    den: "Resident-days",
    dp: 2,
  },
  {
    id: "Q02",
    domain: "Quality & Safety",
    name: "Medication incidents",
    short: "Medication incidents",
    calc: "(Count of medication-related incidents in period / total resident-days in period) x 1,000",
    unit: "Rate per 1,000 resident-days",
    period: "Monthly",
    source: "Incident log (medication category); occupancy record",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Lagging",
    notes: "Use the same resident-days denominator as Q01 so the two are comparable.",
    example: "",
    kloe: "Safe",
    reg: "Reg 12 — Safe care and treatment",
    num: "Medication incidents",
    den: "Resident-days",
    dp: 2,
  },
  {
    id: "Q03",
    domain: "Quality & Safety",
    name: "Safeguarding concerns",
    short: "Safeguarding",
    calc: "(Count of relevant safeguarding concerns raised in period / total resident-days in period) x 1,000",
    unit: "Rate per 1,000 resident-days",
    period: "Monthly",
    source: "Safeguarding log",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Lagging",
    notes: "Confirm whether 'relevant' includes concerns raised but not progressed, or only those formally logged.",
    example: "",
    kloe: "Safe",
    reg: "Reg 13 — Safeguarding",
    num: "Safeguarding concerns",
    den: "Resident-days",
    dp: 2,
  },
  {
    id: "Q04",
    domain: "Workforce",
    name: "Staff absence",
    short: "Staff absence",
    calc: "(Total absence hours in period / total scheduled hours in period) x 100",
    unit: "%",
    period: "Monthly",
    source: "Rota / workforce management system",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Confirm whether authorised leave (annual leave, training days) is excluded from 'absence hours' — it should be.",
    example: "",
    kloe: "Well-led",
    reg: "Reg 18 — Staffing",
    num: "Absence hours",
    den: "Scheduled hours",
    dp: 1,
  },
  {
    id: "Q05",
    domain: "Workforce",
    name: "Agency dependence",
    short: "Agency dependence",
    calc: "(Agency-staff hours worked in period / total hours worked in period) x 100",
    unit: "%",
    period: "Monthly",
    source: "Rota / workforce management system",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Total hours worked = permanent + bank + agency. Confirm bank staff are not counted as agency.",
    example: "",
    kloe: "Well-led",
    reg: "Reg 18 — Staffing",
    num: "Agency hours",
    den: "Total hours worked",
    dp: 1,
  },
  {
    id: "Q06",
    domain: "Workforce",
    name: "Staff turnover",
    short: "Staff turnover",
    calc: "(Leavers in period / average headcount in period) x 100, where average headcount = (headcount at period start + headcount at period end) / 2",
    unit: "%",
    period: "Monthly/Quarterly",
    source: "HR / workforce system",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Decide whether voluntary and involuntary leavers are reported separately or combined; combining hides a meaningful distinction.",
    example: "Home has 40 staff at month start, 36 at month end (avg = 38). 3 staff leave during the month.\nTurnover = 3 / 38 x 100 = 7.9%.",
    kloe: "Well-led",
    reg: "Reg 18 — Staffing",
    num: "Leavers",
    den: "Average headcount",
    dp: 1,
  },
  {
    id: "Q07",
    domain: "Training & Supervision",
    name: "Overdue training",
    short: "Overdue training",
    calc: "(Count of required training items overdue at period end / total required training items) x 100",
    unit: "%",
    period: "Monthly",
    source: "Training / L&D system",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "'Required training' must be a fixed, versioned list per role — if the requirement list changes mid-year, trend comparisons break.",
    example: "",
    kloe: "Effective",
    reg: "Reg 18 — Staffing",
    num: "Overdue training items",
    den: "Required training items",
    dp: 1,
  },
  {
    id: "Q08",
    domain: "Training & Supervision",
    name: "Overdue supervisions",
    short: "Overdue supervisions",
    calc: "(Count of supervisions overdue at period end / total required supervisions) x 100",
    unit: "%",
    period: "Monthly",
    source: "Supervision / HR record",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Define 'overdue' against the home's supervision policy interval (commonly monthly or quarterly per staff member).",
    example: "",
    kloe: "Well-led",
    reg: "Reg 18 — Staffing",
    num: "Overdue supervisions",
    den: "Required supervisions",
    dp: 1,
  },
  {
    id: "Q09",
    domain: "Governance & Audit",
    name: "Overdue actions",
    short: "Overdue actions",
    calc: "(Count of governance/audit actions past their due date at period end / total open actions at period end) x 100",
    unit: "%",
    period: "Monthly",
    source: "Audit / governance action tracker",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Denominator is open actions, not all actions ever raised — closed actions should drop out.",
    example: "",
    kloe: "Well-led",
    reg: "Reg 17 — Good governance",
    num: "Past-due actions",
    den: "Open actions",
    dp: 1,
  },
  {
    id: "Q10",
    domain: "Governance & Audit",
    name: "Recurring audit findings",
    short: "Recurring findings",
    calc: "Count of findings in the current audit cycle that also appeared in the immediately preceding cycle for the same area",
    unit: "Count",
    period: "Monthly/Quarterly",
    source: "Audit / QA records",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Needs a consistent 'finding area' taxonomy across cycles, or recurrence can't be matched automatically.",
    example: "Q1 audit flags 'medication storage temperature not logged' in the medication area.\nQ2 audit again flags 'medication storage temperature not logged' in the same area.\nThis counts as 1 recurring finding for Q2 — matched by area + finding description, not just area alone.",
    kloe: "Well-led",
    reg: "Reg 17 — Good governance",
    num: "Repeated findings",
    den: "",
    dp: 0,
  },
  {
    id: "Q11",
    domain: "Experience",
    name: "Complaints",
    short: "Complaints",
    calc: "(Count of complaints received in period / total resident-days in period) x 1,000",
    unit: "Rate per 1,000 resident-days",
    period: "Monthly",
    source: "Complaints register; occupancy record",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Lagging",
    notes: "Count complaints at the point of receipt, not resolution, so the rate reflects when concerns arose.",
    example: "",
    kloe: "Responsive",
    reg: "Reg 16 — Complaints",
    num: "Complaints received",
    den: "Resident-days",
    dp: 2,
  },
  {
    id: "Q12",
    domain: "Experience",
    name: "Recurring complaint themes",
    short: "Recurring themes",
    calc: "Count of complaints in period tagged with a theme that also appeared in the previous two periods",
    unit: "Count",
    period: "Monthly",
    source: "Complaints register (themed/tagged)",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Requires complaints to be tagged to a fixed theme list at the point of logging — retrofitting themes later will be unreliable.",
    example: "March complaints: 2 tagged 'call bell response time'.\nApril complaints: 3 tagged 'call bell response time'.\nMay complaints: 1 tagged 'call bell response time'.\nMay's count of 1 is recurring because the same theme appeared in March and April (the two preceding periods) — flag regardless of whether May's count is itself high.",
    kloe: "Responsive",
    reg: "Reg 16 — Complaints",
    num: "Repeated themes",
    den: "",
    dp: 0,
  },
  {
    id: "Q13",
    domain: "Experience",
    name: "Satisfaction",
    short: "Satisfaction",
    calc: "Mean of the most recent resident/family satisfaction survey responses, standardised to a 0-100 scale",
    unit: "Score (0-100)",
    period: "Monthly/Quarterly",
    source: "Satisfaction survey",
    missing: "If no survey was run in the period, carry forward the last available score but flag it as 'stale' rather than treating it as a fresh reading.",
    harm: "Lower = worse",
    type: "Outcome",
    notes: "Survey instrument and scale need to be fixed before launch, or scores aren't comparable month to month.",
    example: "",
    kloe: "Caring",
    reg: "Reg 9 — Person-centred care",
    num: "Survey mean",
    den: "",
    dp: 0,
  },
  {
    id: "Q14",
    domain: "Operational",
    name: "Delayed/missed activities",
    short: "Missed activities",
    calc: "(Count of scheduled care activities delayed or missed in period / total scheduled activities in period) x 100",
    unit: "%",
    period: "Monthly",
    source: "Care planning / activity log",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Potential leading",
    notes: "Scope to activities the home already logs (e.g. care rounds, planned activities) — don't introduce a new logging burden for MVP.",
    example: "",
    kloe: "Responsive",
    reg: "Reg 9 — Person-centred care",
    num: "Delayed or missed activities",
    den: "Scheduled activities",
    dp: 1,
  },
  {
    id: "Q15",
    domain: "Regulatory",
    name: "Open findings/actions",
    short: "Open regulatory items",
    calc: "Count of open CQC or other regulatory findings/actions at period end",
    unit: "Count",
    period: "Monthly/Quarterly",
    source: "CQC portal / inspection and action records",
    missing: "If the numerator or denominator is missing or not submitted for the period, do not calculate a value. Mark the indicator as 'insufficient data' for that period. Never impute zero or carry forward the previous value.",
    harm: "Higher = worse",
    type: "Lagging/context",
    notes: "Treat as context alongside the other 14, not as a standalone trend — inspection cadence is irregular, unlike the operational indicators.",
    example: "",
    kloe: "Well-led",
    reg: "Reg 17 — Good governance",
    num: "Open findings/actions",
    den: "",
    dp: 0,
  },
] as const;

export const INDICATOR_BY_ID: ReadonlyMap<string, Indicator> = new Map(
  INDICATORS.map((i) => [i.id, i]),
);

export function getIndicator(id: string): Indicator {
  const ind = INDICATOR_BY_ID.get(id);
  if (!ind) throw new Error(`Unknown indicator id: ${id}`);
  return ind;
}

export const INDICATOR_IDS: readonly string[] = INDICATORS.map((i) => i.id);

/** Domains in the order the source specification lists them. */
export const DOMAINS = [
  'Quality & Safety',
  'Workforce',
  'Training & Supervision',
  'Governance & Audit',
  'Experience',
  'Operational',
  'Regulatory',
] as const;

export const KEY_QUESTIONS = ['Safe', 'Effective', 'Caring', 'Responsive', 'Well-led'] as const;
