import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

/**
 * Object storage.
 *
 * Local disk in development, behind a narrow interface so production can swap
 * in S3 or Azure Blob without touching the routes. Keys are generated by the
 * caller and are never derived from a user-supplied filename.
 */

const ROOT = resolve(process.cwd(), '.storage');

/** Refuses any key that would escape the storage root. */
function pathFor(key: string): string {
  const target = resolve(join(ROOT, key));
  if (target !== ROOT && !target.startsWith(ROOT + sep)) {
    throw new Error('Refusing a storage key that escapes the storage root');
  }
  return target;
}

export async function storeObject(key: string, body: Buffer): Promise<void> {
  const target = pathFor(key);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, body, { flag: 'wx' });
}

export async function readObject(key: string): Promise<Buffer | null> {
  try {
    return await readFile(pathFor(key));
  } catch {
    return null;
  }
}
